apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: mern-ecommerce-frontend:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 80
