apiVersion: v1
kind: Service
metadata:
  name: shopcart-frontend-service
  namespace: shopcart
spec:
  type: NodePort
  selector:
    app: shopcart-frontend
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: shopcart-backend-service
  namespace: shopcart
spec:
  type: ClusterIP
  selector:
    app: shopcart-backend
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: shopcart-mongo
  namespace: shopcart
spec:
  type: ClusterIP
  selector:
    app: shopcart-mongo
  ports:
  - port: 27017
    targetPort: 27017