  apiVersion: v1
  kind: Pod
  metadata:
    name: backend
    labels:
      app: backend
  spec:
    containers:
    - name: backend
      image: mern-ecommerce-backend:latest
      imagePullPolicy: Never
      ports:
      - containerPort: 5000
      env:
      - name: PORT
        value: "5000"
      - name: MONGO_URI
        value: "mongodb://database:27017/ecommercedb"
      readinessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /health
          port: 5000
        initialDelaySeconds: 15
        periodSeconds: 10