name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: [self-hosted, macos, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's Docker daemon..."
        eval $(minikube docker-env)

    - name: Build Docker images
      run: |
        cd app/frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/shopcart-frontend:latest --platform linux/arm64 .
        cd ../backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/shopcart-backend:latest --platform linux/arm64 .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/shopcart-frontend:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/shopcart-backend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
